### ISSUE TITLE
Message not loggued from http_bind connection

### ISSUE THREAD

**Issue by PoGo606** [candy-chat/mod_log_chat_mysql5#12]
Hi there,

I've a problem when using the http_bind connection through "jappix" web app the log are not saved in the DB.
When using a regular client like pidgin, the conversation are logged.

I tried to search some similar errors on the web, and I found this : https://github.com/processone/ejabberd-contrib/issues/9

Do you think it could be related ?

**Comment by mweibel** [comment]
Closing after inactivity
