### ISSUE TITLE
Crash Report in ejabberd

### ISSUE THREAD

**Issue by kishoreacesurf** [candy-chat/mod_log_chat_mysql5#17]
Hi, 

I am getting this crash report when using this module. Please help me with this. 

=CRASH REPORT==== 19-Aug-2015::06:45:12 ===
  crasher:
    initial call: mod_log_chat_mysql5:init/1
    pid: <0.3622.0>
    registered_name: 'mod_log_chat_mysql5_xmpp.yellowmssngr.com'
    exception exit: {bad_return_value,
                        {failed_to_connect_to_database,etimedout}}
      in function  gen_server:init_it/6
    ancestors: [ejabberd_sup,<0.37.0>]
    messages: []
    links: [<0.276.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 24
    reductions: 543
  neighbours:

crasher:
    initial call: mod_log_chat_mysql5:init/1
    pid: <0.425.0>
    registered_name: 'mod_log_chat_mysql5_xmpp.yellowmssngr.com'
    exception exit: {connection_down,
                        {and_conn_reset_failed,
                            {cannot_reopen_in_reset,
                                {failed_to_connect_to_database,etimedout}}}}
      in function  gen_server:terminate/6
    ancestors: [ejabberd_sup,<0.37.0>]
    messages: [{'$gen_cast',
                      {insert_row,"res_f_10152837794923223","delyver",
                          "Are you open now?","chat"}},
                  {'$gen_cast',
                      {insert_row,"reply1","replysona",
                          "{\"businessUsername\":\"delyver\",\"location\":\"13.0019099,77.7131591\",\"message\":\"Are you open now?\",\"username\":\"res_f_10152837794923223\",\"businessName\":\"Delyver\",\"userFullName\":\"Kishore Jaya\",\"placeId\":\"190\"}",
                          "chat"}},
                  {'$gen_cast',
                      {insert_row,"replykishore","reply1",
                          "{\"message\":\"hello \",\"from\":\"hungrybells\",\"name\":\"Hungry Bells\",\"username\":\"res_p_3248652080\"}",
                          "chat"}},
                  {'$gen_cast',
                      {insert_row,"reply1","res_p_3248652080",
                          "{\"message\":\"hello \",\"from\":\"hungrybells\",\"name\":\"Hungry Bells\",\"username\":\"res_p_3248652080\"}",
                          "chat"}}]

**Comment by mweibel** [comment]
You should learn to read the erlang stacktraces, I know they're a bit painful, but yeah ;) 
The interesting bit is:

```
{connection_down,
{and_conn_reset_failed,
{cannot_reopen_in_reset,
{failed_to_connect_to_database,etimedout}}}}
```

i.e. it can't connect to your MySQL database.
